-- Clodeaniea 3 : Ethnicity

CREATE TABLE CLODEANIEA3(
						 ETHNICITY varchar(30) PRIMARY KEY NOT NULL,
						 PERCENTAGE float NOT NULL,
						 POPULATION BIGINT); 
						 
SELECT * FROM CLODEANIEA3;

INSERT INTO CLODEANIEA3
VALUES 
('White',	45,	214048140),
('Black',	27,	128428884),
('Asian (Oriental)', 3.4, 16172527),
('Asian (Non-Oriental)',	3.9,	18550839),
('Mixed', 	13,	61836130),
('Other',	7.7,	36626015);

SELECT * FROM CLODEANIEA3;

SELECT AVG(POPULATION) FROM CLODEANIEA3;

SELECT MAX(POPULATION) FROM CLODEANIEA3;

SELECT MIN(POPULATION) FROM CLODEANIEA3;

--- Population with minimum poulation
SELECT * FROM CLODEANIEA3 ORDER BY POPULATION LIMIT 1; 

--- Population with maximum population
SELECT * FROM CLODEANIEA3 ORDER BY POPULATION DESC LIMIT 1;